### ISSUE TITLE
error after runnning dcl start

### ISSUE THREAD

**Issue by emtechgroup** [decentraland-scenes/Awesome-Repository#2]
Error [AssertionError]: Assertion failed
    at new goog.asserts.AssertionError (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:2574054)
    at Object.goog.asserts.doAssertFailure_ (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:2574606)
    at Object.goog.asserts.assert (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:2574872)
    at jspb.BinaryReader.readEnum (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:2654267)
    at Function.proto.protocol.SubscriptionMessage.deserializeBinaryFromReader (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:2521613)
    at Function.proto.protocol.SubscriptionMessage.deserializeBinary (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:2521381)
    at WebSocket.<anonymous> (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:2358426)
    at WebSocket.emit (node:events:378:20)
    at Receiver.L (/usr/local/lib/node_modules/decentraland/dist/cli.js:3:652466)
    at Receiver.emit (node:events:378:20) {
  reportErrorToServer: true,
  messagePattern: 'Assertion failed'
}

I run npm install -g decentraland and then run 'dcl start', i recieve error message above. Also when first time running scene metamask requests a sign in to connect to the local scene. Any advice would be greatly appreciated!

**Comment by nearnshaw** [comment]
This issue is lacking context, and is a year old. I'm goin to close it

If still experiencing this issue, please ask for help in Discord, in the SDK channel you're sure to find help
